# gen_pvz_data.py — 从 docs/data/*.json 生成 Content/Scripts/pvz_data.rx
# 纪律:rx host 脚本仅支持标量四则/比较/if-else/let/as 转换;禁止 floor/min/max/abs 等内建;
# 导出函数必须自包含(无跨函数调用)。本生成器是唯一事实源通路,手改 pvz_data.rx 会被覆盖。
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "data"
OUT = ROOT / "Content" / "Scripts" / "pvz_data.rx"

plants = json.loads((DATA / "plants.json").read_text(encoding="utf-8"))
zombies = json.loads((DATA / "zombies.json").read_text(encoding="utf-8"))
levels = json.loads((DATA / "levels.json").read_text(encoding="utf-8"))
stages = json.loads((DATA / "stages.json").read_text(encoding="utf-8"))

plant_id = {p["id"]: i + 1 for i, p in enumerate(plants)}          # 1..49
zombie_id = {z["id"]: i + 1 for i, z in enumerate(zombies)}        # 1..26
stage_code = {s["id"]: i + 1 for i, s in enumerate(stages)}        # day=1 night=2 pool=3 fog=4 roof=5

SPECIALS = ["conveyor", "bowling", "whack", "big_trouble", "vasebreaker", "storm",
            "bobsled", "boss", "tutorial_1lane", "tutorial_3lane", "minigame_unlock",
            "puzzle_unlock", "shop_unlock", "zen_garden_unlock"]
special_code = {name: i + 1 for i, name in enumerate(SPECIALS)}     # 0 = none

NON_PLANT_REWARDS = ["note", "shovel", "almanac", "shop_key", "taco", "watering_can", "silver_trophy"]
reward_code = {name: 100 + i for i, name in enumerate(NON_PLANT_REWARDS)}

SPEEDS = ["slow", "normal", "fast", "very_fast"]
speed_code = {s: i + 1 for i, s in enumerate(SPEEDS)}

RANGES = ["none", "self", "touch", "lane", "3x3", "whole_screen"]
range_code = {r: i for i, r in enumerate(RANGES)}                   # 动态扩充未知 range
for p in plants:
    r = str(p.get("range") or "none")
    if r not in range_code:
        range_code[r] = len(range_code)

def level_code_of(level_id: str) -> int:
    stage_s, num_s = level_id.split("-")[0], level_id.split("-")[1]
    return int(stage_s) * 100 + int(num_s)

def unlock_code(u: str) -> int:
    if not u:
        return 0
    u = str(u).strip()
    if u == "shop":
        return 999
    if "二周目" in u:
        base = u.split()[0]
        return 1000 + level_code_of(base)
    try:
        return level_code_of(u)
    except Exception:
        return 0

def fnum(v) -> str:
    if v is None:
        return "0.0"
    f = float(v)
    return repr(f) if not f.is_integer() else f"{int(f)}.0"

def emit_query(name: str, pairs, default: float = 0.0) -> str:
    """pairs: list[(id:int, value:float)] → 按值分组的 if 链查询函数。"""
    groups = {}
    for i, v in pairs:
        groups.setdefault(float(v), []).append(i)
    lines = [f"#[export(c)]", f"pub fn {name}(id: f32) -> f32 {{"]
    for value in sorted(groups):
        ids = groups[value]
        cond = " || ".join(f"id == {float(i)}" for i in ids)
        lines.append(f"    if {cond} {{ return {fnum(value)}; }}")
    lines.append(f"    return {fnum(default)};")
    lines.append("}")
    return "\n".join(lines)

def armor_value(z) -> float:
    a = z.get("armor")
    if isinstance(a, (int, float)):
        return float(a)
    if isinstance(a, str):
        # 保留资料中明确写出的护甲吸收量；纯描述且无数值仍如实返回 0(未知)。
        import re
        m = re.search(r"(\d+)", a)
        if m:
            return float(m.group(1))
    return 0.0

def production_field(p, field):
    prod = p.get("production")
    if isinstance(prod, dict):
        v = prod.get(field)
        if isinstance(v, (int, float)):
            return float(v)
    return 0.0

parts = []
parts.append("// Generated by tools/gen_pvz_data.py from docs/data/*.json — 勿手改。")
parts.append("// 编码:植物 id=1..49(数组序),僵尸 id=1..26,关卡 code=stage*100+num(1-1=101..5-10=510),场景 day=1 night=2 pool=3 fog=4 roof=5。")
parts.append("// special: 0=none " + " ".join(f"{i+1}={n}" for i, n in enumerate(SPECIALS)))
parts.append("// reward: 植物=植物id(1..49); " + " ".join(f"{100+i}={n}" for i, n in enumerate(NON_PLANT_REWARDS)))
parts.append("// speed: " + " ".join(f"{i+1}={s}" for i, s in enumerate(SPEEDS)) + "; range: " + " ".join(f"{c}={r}" for r, c in sorted(range_code.items(), key=lambda kv: kv[1])))
parts.append("")
parts.append("fn main() {}")
parts.append("")

# ---- 植物 ----
parts.append(emit_query("plant_cost", [(plant_id[p["id"]], p["cost"]) for p in plants]))
parts.append(emit_query("plant_recharge", [(plant_id[p["id"]], p["recharge_sec"]) for p in plants]))
parts.append(emit_query("plant_hp", [(plant_id[p["id"]], p["hp"]) for p in plants]))
parts.append(emit_query("plant_damage", [(plant_id[p["id"]], p["damage"]) for p in plants]))
parts.append(emit_query("plant_attack_interval", [(plant_id[p["id"]], p["attack_interval_sec"]) for p in plants]))
parts.append(emit_query("plant_range_code", [(plant_id[p["id"]], range_code[str(p.get("range") or "none")]) for p in plants]))
parts.append(emit_query("plant_production_amount", [(plant_id[p["id"]], production_field(p, "sun")) for p in plants]))
parts.append(emit_query("plant_production_interval", [(plant_id[p["id"]], production_field(p, "interval_sec")) for p in plants]))
parts.append(emit_query("plant_unlock_code", [(plant_id[p["id"]], unlock_code(p.get("unlock"))) for p in plants]))
parts.append(emit_query("plant_mushroom", [(plant_id[p["id"]], 1 if p.get("mushroom") else 0) for p in plants]))
parts.append(emit_query("plant_aquatic", [(plant_id[p["id"]], 1 if p.get("aquatic") else 0) for p in plants]))
parts.append(emit_query("plant_upgrade_code", [(plant_id[p["id"]], plant_id.get(p.get("upgrade_from") or "", 0)) for p in plants]))

# ---- 僵尸 ----
parts.append(emit_query("zombie_hp", [(zombie_id[z["id"]], z["hp"]) for z in zombies]))
parts.append(emit_query("zombie_speed_code", [(zombie_id[z["id"]], speed_code.get(str(z.get("speed") or "normal"), 2)) for z in zombies]))
parts.append(emit_query("zombie_dps", [(zombie_id[z["id"]], z["dps"]) for z in zombies]))
parts.append(emit_query("zombie_armor", [(zombie_id[z["id"]], armor_value(z)) for z in zombies]))
parts.append(emit_query("zombie_special_code", [(zombie_id[z["id"]], zombie_id[z["id"]]) for z in zombies]))  # 特殊行为枚举 = 僵尸 id 本身
parts.append(emit_query("zombie_first_level_code", [(zombie_id[z["id"]], unlock_code(z.get("first_level"))) for z in zombies]))

# ---- 关卡 ----
lcodes = [(level_code_of(l["id"]), l) for l in levels]
parts.append(emit_query("level_waves", [(c, l["waves"]) for c, l in lcodes]))
parts.append(emit_query("level_flags", [(c, l["flags"]) for c, l in lcodes]))
parts.append(emit_query("level_starting_sun", [(c, l.get("starting_sun", 50)) for c, l in lcodes]))
parts.append(emit_query("level_stage_code", [(c, stage_code[l["stage"]]) for c, l in lcodes]))
parts.append(emit_query("level_special_code", [(c, special_code.get(str(l.get("special_rules") or ""), 0)) for c, l in lcodes]))

def reward_value(l):
    r = str(l.get("reward") or "")
    if r in plant_id:
        return plant_id[r]
    return reward_code.get(r, 0)
parts.append(emit_query("level_reward_code", [(c, reward_value(l)) for c, l in lcodes]))
parts.append(emit_query("level_zombie_count", [(c, len(l.get("zombie_ids") or [])) for c, l in lcodes]))

# level_zombie_at_packed(pack) — pack = level_code*100 + index(单动态参,图侧 var 累加构造)
lines = ["#[export(c)]", "pub fn level_zombie_at_packed(pack: f32) -> f32 {"]
for c, l in sorted(lcodes):
    zids = l.get("zombie_ids") or []
    for i, zid in enumerate(zids):
        lines.append(f"    if pack == {float(c * 100 + i)} {{ return {float(zombie_id[zid])}; }}")
lines.append("    return 0.0;")
lines.append("}")
parts.append("\n".join(lines))

# ---- 场景 ----
parts.append(emit_query("stage_rows", [(stage_code[s["id"]], s["rows"]) for s in stages]))
parts.append(emit_query("stage_cols", [(stage_code[s["id"]], s["cols"]) for s in stages]))
parts.append(emit_query("stage_sky_sun_enabled", [(stage_code[s["id"]], 1 if (s.get("sky_sun") or {}).get("enabled") else 0) for s in stages]))
parts.append(emit_query("stage_sky_sun_interval", [(stage_code[s["id"]], (s.get("sky_sun") or {}).get("interval_sec", 0)) for s in stages]))
parts.append(emit_query("stage_sky_sun_amount", [(stage_code[s["id"]], (s.get("sky_sun") or {}).get("amount", 0)) for s in stages]))
parts.append(emit_query("stage_fog_columns", [(stage_code[s["id"]], s.get("fog_columns", 0)) for s in stages]))
parts.append(emit_query("stage_roof_slope_cols", [(stage_code[s["id"]], s.get("roof_slope_cols", 0)) for s in stages]))

OUT.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
print(f"OK wrote {OUT} plants={len(plants)} zombies={len(zombies)} levels={len(levels)} stages={len(stages)}")
