/** Strict original RGBA comparison; no tolerances silently approve changed pixels. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {hash,decodeEvidencePng,compareRgba} from './frozen_pixel_cases.mjs';
const arg=name=>{const i=process.argv.indexOf(name);assert.ok(i>=0&&process.argv[i+1],'Missing '+name);return process.argv[i+1];};
const aPath=path.resolve(arg('--baseline')),bPath=path.resolve(arg('--candidate')),out=path.resolve(arg('--out'));assert.ok(!fs.existsSync(out),'Preserve prior comparison');const aBytes=fs.readFileSync(aPath),bBytes=fs.readFileSync(bPath),a=JSON.parse(aBytes),b=JSON.parse(bBytes);
const subset=process.argv.includes('--allow-candidate-subset');assert.equal(a.schemaVersion,1);assert.equal(b.schemaVersion,1);assert.equal(a.resourceManifestSha256,b.resourceManifestSha256,'Content manifest changed');assert.equal(a.runtimeIndexSha256,b.runtimeIndexSha256,'Runtime image index changed');if(!subset)assert.equal(a.cases.length,b.cases.length);assert.ok(!a.errors?.length&&!b.errors?.length);
const baseline=new Map(a.cases.map(c=>[c.id,c]));assert.equal(baseline.size,a.cases.length);const seen=new Set(),results=[];
for(const c of b.cases){assert.ok(!seen.has(c.id));seen.add(c.id);const old=baseline.get(c.id);assert.ok(old,'Unknown case '+c.id);for(const key of ['snapshotSha256','tick','width','height'])assert.equal(c[key],old[key],key+' changed: '+c.id);assert.deepEqual(c.view,old.view,'Camera changed');assert.deepEqual(c.expected,old.expected,'Expected frame/geometry changed');assert.ok(old.stability?.exact&&c.stability?.exact,'Unstable wall-time baseline');const oldBytes=fs.readFileSync(old.baselinePng),newBytes=fs.readFileSync(c.baselinePng);assert.equal(hash(oldBytes),old.baselinePngSha256);assert.equal(hash(newBytes),c.baselinePngSha256);const av=decodeEvidencePng(oldBytes),bv=decodeEvidencePng(newBytes);assert.equal(av.width,c.width);assert.equal(av.height,c.height);assert.equal(bv.width,c.width);assert.equal(bv.height,c.height);assert.equal(hash(av.raw),old.baselineRgbaSha256);assert.equal(hash(bv.raw),c.baselineRgbaSha256);results.push({id:c.id,...compareRgba(av.raw,bv.raw,c.width,c.height)});}
const report={schemaVersion:1,scope:'Strict same-input/camera/tick lossless native RGBA comparison. No pixels ignored within tested cases; no gameplay, balance or FPS claim.',baseline:{path:aPath,sha256:hash(aBytes),engineHash:a.engineHash,totalCases:a.cases.length},candidate:{path:bPath,sha256:hash(bBytes),engineHash:b.engineHash},explicitCandidateSubset:subset,uncomparedBaselineCases:a.cases.filter(c=>!seen.has(c.id)).map(c=>c.id),cases:results.length,exactCases:results.filter(r=>r.exact).length,changedCases:results.filter(r=>!r.exact),pass:results.every(r=>r.exact)};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,uncomparedBaselineCases:report.uncomparedBaselineCases.length,changedCases:report.changedCases.length,report:out}));if(!report.pass)process.exitCode=1;
