/** Lossless, explicitly unearned render fixtures. No gameplay or timing claims. */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
export const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const option=(key,fallback=null)=>{const i=process.argv.indexOf(key);return i<0?fallback:process.argv[i+1];};
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
const crc=bytes=>{let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
function chunk(tag,data){const name=Buffer.from(tag),size=Buffer.alloc(4),check=Buffer.alloc(4);size.writeUInt32BE(data.length);check.writeUInt32BE(crc(Buffer.concat([name,data])));return Buffer.concat([size,name,data,check]);}
export function encodePng(raw,width,height){assert.equal(raw.length,width*height*4);const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const scan=Buffer.alloc(height*(width*4+1));for(let y=0;y<height;y++)raw.copy(scan,y*(width*4+1)+1,y*width*4,(y+1)*width*4);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(scan,{level:2})),chunk('IEND',Buffer.alloc(0))]);}
/** Only our filter-0 RGBA8 GPU evidence PNGs; no lossy/image-edit path. */
export function decodeEvidencePng(bytes){assert.ok(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])));let p=8,width,height,parts=[];while(p<bytes.length){const size=bytes.readUInt32BE(p),type=bytes.subarray(p+4,p+8),data=bytes.subarray(p+8,p+8+size);assert.equal(bytes.readUInt32BE(p+8+size),crc(Buffer.concat([type,data])));if(type.toString()==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);assert.equal(data[8],8);assert.equal(data[9],6);assert.equal(data[12],0);}if(type.toString()==='IDAT')parts.push(data);p+=12+size;}assert.equal(p,bytes.length);const scan=zlib.inflateSync(Buffer.concat(parts)),stride=width*4+1,raw=Buffer.alloc(width*height*4);assert.equal(scan.length,stride*height);for(let y=0;y<height;y++){assert.equal(scan[y*stride],0);scan.copy(raw,y*width*4,y*stride+1,(y+1)*stride);}return{raw,width,height};}
export function compareRgba(a,b,width,height){assert.equal(a.length,width*height*4);assert.equal(b.length,a.length);let changedPixels=0,changedChannels=0,totalDelta=0,maxDelta=0,left=width,top=height,right=0,bottom=0;const examples=[];for(let i=0;i<a.length;i+=4){let changed=false;for(let c=0;c<4;c++){const d=Math.abs(a[i+c]-b[i+c]);if(d){changed=true;changedChannels++;totalDelta+=d;maxDelta=Math.max(maxDelta,d);}}if(changed){changedPixels++;const pixel=i/4,x=pixel%width,y=Math.floor(pixel/width);left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x+1);bottom=Math.max(bottom,y+1);if(examples.length<12)examples.push({x,y,baseline:[...a.subarray(i,i+4)],candidate:[...b.subarray(i,i+4)]});}}return{exact:changedPixels===0,changedPixels,changedChannels,maxByteDelta:maxDelta,meanAbsoluteByteDelta:totalDelta/a.length,differenceBbox:changedPixels?[left,top,right,bottom]:null,examples};}
export function fixtureWriter({project,captureDir,width,height,view,engineHash}){
 const requested=option('--export-cases');if(!requested)return null;
 const out=path.join(path.resolve(requested),path.basename(captureDir));assert.ok(!fs.existsSync(out),'Preserve existing fixed fixture export');fs.mkdirSync(out,{recursive:true});
 const manifest={schemaVersion:1,kind:'frozen-native-rgba-cases',scope:'Exact saved replica snapshots and lossless native RGBA. Explicitly unearned visual fixtures, not simulation/operating economy or FPS proof.',engineHash,captureDir,width,height,view,wallTimePolicy:'Snapshot.playback.paused and winner=null; no play.pause. Repeated real readback after150ms must equal the first image. Optimized consumer must reopen a fresh replica per case to clear interpolation and old ghosts.',resourceManifestSha256:hash(fs.readFileSync(path.join(project,'Content/UI/v6/resource-manifest.json'))),runtimeIndexSha256:hash(fs.readFileSync(path.join(project,'Content/Animations/v6/runtime-frames/index.json'))),cases:[]};
 return{async append(name,snapshot,expected,firstRaw,pngPath,readAgain){assert.match(name,/^[a-z0-9-]+$/);assert.equal(snapshot.winner,null);assert.equal(snapshot.playback?.paused,true);const input=Buffer.from(JSON.stringify(snapshot)),file=path.join(out,name+'.snapshot.json.gz'),compressed=zlib.gzipSync(input,{level:1});fs.writeFileSync(file,compressed);await new Promise(r=>setTimeout(r,150));const repeated=await readAgain();const stability=compareRgba(firstRaw,repeated,width,height);if(!stability.exact)fs.writeFileSync(path.join(out,name+'-unstable-repeat.png'),encodePng(repeated,width,height));manifest.cases.push({id:name,tick:snapshot.tick,width,height,view,expected,snapshotPath:file,snapshotSha256:hash(input),compressedSnapshotSha256:hash(compressed),baselinePng:pngPath,baselinePngSha256:hash(fs.readFileSync(pngPath)),baselineRgbaSha256:hash(firstRaw),repeatedRgbaSha256:hash(repeated),stability});fs.writeFileSync(path.join(out,'cases.json'),JSON.stringify(manifest,null,2));assert.ok(stability.exact,'Wall-time drift in frozen fixture '+name);},out};
}
