import fs from 'node:fs';import path from 'node:path';import zlib from 'node:zlib';import {createHash} from 'node:crypto';
import {launchNative} from '../../game/v6/native-rpc.mjs';
import {fixtureWriter} from './frozen_pixel_cases.mjs';
export const sha=b=>createHash('sha256').update(b).digest('hex');
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function chunk(type,data){const name=Buffer.from(type),size=Buffer.alloc(4),crc=Buffer.alloc(4);size.writeUInt32BE(data.length);let c=0xffffffff;for(const b of Buffer.concat([name,data]))c=table[(c^b)&255]^(c>>>8);crc.writeUInt32BE((c^0xffffffff)>>>0);return Buffer.concat([size,name,data,crc]);}
export function png(rgba,w,h){const header=Buffer.alloc(13);header.writeUInt32BE(w);header.writeUInt32BE(h,4);header[8]=8;header[9]=6;const scan=Buffer.alloc(h*(w*4+1));for(let y=0;y<h;y++)rgba.copy(scan,y*(w*4+1)+1,y*w*4,(y+1)*w*4);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(scan,{level:2})),chunk('IEND',Buffer.alloc(0))]);}
export const view={centerX:64,centerY:48,zoom:4,layer:0,cutaway:true,localPlayer:1};
export const width=1920,height=1080;
export const option=(key,fallback)=>{const i=process.argv.indexOf(key);return i<0?fallback:process.argv[i+1];};
export function clean(s){s=structuredClone(s);for(const k of ['buildings','rooms','units','links','walls','entrances','resources','shipments','projectiles','events','jobs','rubble','defenseFields','shieldRegions','networkStores','powerGrids','excavated'])s[k]=[];s.excavationOwners={};s.terrain.fill(3);s.winner=null;s.winReason='';const all=[];for(let y=0;y<96;y++)for(let x=0;x<128;x++)all.push({x,y,z:0});s.visible=[all,all];s.explored=[all,all];s.tick=0;s.revision=0;s.playback={paused:true,speed:1,currentTick:0,totalTicks:10000000};return s;}
export const projectPoint=([x,y,z])=>[width/2+((x-y)*.5-(view.centerX-view.centerY)*.5)*90,height/2-(-(x+y)*.25+z*1.5+(view.centerX+view.centerY)*.25)*90];
export async function session(label,{retainPixels=false}={}){const project=path.resolve('projects/code-sentinels'),out=path.join(project,'Logs/v6',option('--run',label));const executable=path.resolve(option('--engine',path.join(project,'game/v6/runtime-bin/engine-host.exe')));const hash=option('--engine-hash','9974933a7c984103c6bc09592ce78a6f6ba809ce8e3fc5ef1341220db88fdffc');if(sha(fs.readFileSync(executable))!==hash)throw Error('Unexpected fixed engine hash');fs.mkdirSync(out,{recursive:true});const native=await launchNative({root:project,executable,logs:path.join(out,'engine')});const rpc=(method,p={},timeout=60000)=>native.rpc(method,p,timeout);const opened=await rpc('game.session.open',{mode:'replica',seed:611006,theme:'river',localPlayer:1,opponent:'human'});await rpc('game.session.view',view);const base=clean(opened.snapshot);const report={scope:'Explicit unearned visual fixture, native Rurix GPU readback only. Not gameplay/economy/network/performance acceptance.',engineHash:hash,pid:native.pid,port:native.port,view,width,height,captures:[],errors:[],startedAt:new Date().toISOString()};
const fixedCases=fixtureWriter({project,captureDir:out,width,height,view,engineHash:hash});
const save=()=>fs.writeFileSync(path.join(out,'capture-report.json'),JSON.stringify(report,null,2));
async function capture(name,s,expected=[]){if(fixedCases){await rpc('game.session.close');await rpc('game.session.open',{mode:'replica',seed:s.seed,theme:s.theme,localPlayer:view.localPlayer,opponent:'human'});await rpc('game.session.view',view);}await rpc('game.session.applySnapshot',{snapshot:s});const f=await rpc('viewport.frame',{width,height,format:'rgba8'},120000);const raw=Buffer.from(f.pixelsB64,'base64');if(raw.length!==width*height*4||f.width!==width||f.height!==height||f.meshFallbacks||f.truncated)throw Error('Unexpected native viewport output');delete f.pixelsB64;const file=name+'.png';const data=png(raw,width,height);fs.writeFileSync(path.join(out,file),data);const entry={file,tick:s.tick,revision:s.revision,rgbaSha256:sha(raw),pngSha256:sha(data),diagnostics:f,expected};if(retainPixels)Object.defineProperty(entry,"rgba",{value:raw,enumerable:false});report.captures.push(entry);save();if(fixedCases)await fixedCases.append(name,s,expected,raw,path.join(out,file),async()=>{const r=await rpc('viewport.frame',{width,height,format:'rgba8'},120000);if(r.meshFallbacks||r.truncated)throw Error('Repeated native frame failed');return Buffer.from(r.pixelsB64,'base64');});return entry;}
return {project,out,rpc,native,base,report,capture,save};}
