"""Observed front-walk failure: prompt actual distinct leg motion with concise positive wording."""
from media import *
id='gpt-s-walk-march-v2';folder=HERE/'jobs'/id;ref='pipeline/v6/first-frames/gpt-s.png'
if not (folder/'attempt.json').exists():
 prompt=('The small white-haired figure marches in place facing directly toward the viewer. Her RIGHT FOOT rises to the height of the other calf while the right knee bends forward, then the right foot comes down to its original mark. Next her LEFT FOOT rises the same way and comes down. Repeat this alternating right-left march twice. Both legs and both feet remain individually visible. Her arms swing gently opposite the stepping legs; long hair follows the physical motion. Her outline changes naturally with each clearly visible raised-knee stride. '
 'Keep her face, hair, white/lavender costume, boots and existing ornaments exactly as pictured. Keep the body centered at its original size and facing straight forward for the entire sequence. '
 'The only scene is this single figure on a completely featureless, uniform bright green backdrop. Every background pixel stays RGB0,255,0. The elevated orthographic camera and studio lighting stay fixed. Start marching immediately and finish the fourth stride by4 seconds, returning to the original standing posture.')
 save(folder/'request.json',{'id':id,'category':'character','character':'gpt','direction':'s','action':'walk','firstFrame':ref,'lastFrame':ref,'prompt':prompt,'frames':124,'width':384,'height':384,'fps':24,'segments':{'walk':[0,112,32,True]},'priorityFront':True,'revisionReason':'Actual prior source froze the legs and animated colored backdrop circles. This concise physical marching prompt explicitly changes leg silhouette without the contradictory preserve-silhouette wording.'});submit(folder)
old=HERE/'jobs'/'gpt-s-walk-body-v1';receipt=read(old/'video.json');save(old/'source-review.json',{'id':old.name,'approved':False,'reviewedAt':stamp(),'reason':'Legs do not perform a complete visible walk cycle; background changes to cyan, magenta, red and yellow circles. Cannot be used as a keyed walking clip.','videoSha256':receipt['sha256']})
overrides=read(HERE/'action-overrides.json');overrides['gpt/s/walk']=id;save(HERE/'action-overrides.json',overrides)
