import {useEffect,useState} from 'react';
import {ArrowRight,BookOpen,Check,ChevronRight,Clock3,FolderOpen,Layers3,Play,Radio,Shield,Swords,Users,X} from 'lucide-react';
import type {V6Catalog,V6Session,V6SessionOptions,V6Snapshot} from '@/lib/sentinelsV6';
import {V6_BRANCHES,V6_SKILL_NAMES,formatV6,timeV6} from '@/lib/sentinelsV6';
import {v6Request} from '@/lib/useSentinelsV6';
import V6Card,{V6_ART,v6CardImage} from './V6Card';
import V6Guide from './V6Guide';

type Props={session:V6Session|null;snapshot:V6Snapshot|null;playerId:number;catalog:V6Catalog;busy:boolean;error:string;connected:boolean;onBegin:(value:V6SessionOptions)=>Promise<boolean>;onContinue:()=>void;onAction:(name:string,body?:unknown)=>Promise<unknown>;onRefresh:()=>void};
type SaveEntry={id:string;name?:string;tick?:number;compatible?:boolean;compatibility?:'compatible'|'legacy-unverified'|'incompatible'|'engine-unverified';compatibilityReason?:string};
const THEMES=[{id:'river',name:'镜河交界',subtitle:'RIVER / BORDER',text:'河谷两岸的机房与运输线。控制桥梁和水电，打开中央科研走廊。'},{id:'mining',name:'深矿断层',subtitle:'MINING / FAULT',text:'沿煤层扩展地下室，在矿井入口与货运通道争夺下一轮补给。'},{id:'highland',name:'穹顶高地',subtitle:'HIGHLAND / SKY',text:'高地风电与多层堡垒。夺取制高点，在空地协同中逼近对方核心。'}];
export default function V6Lobby(p:Props){
  const[tab,setTab]=useState<'operations'|'archive'|'guide'>('operations'),[mode,setMode]=useState<'solo'|'host'|'join'>('solo'),[theme,setTheme]=useState('river'),[seed,setSeed]=useState(6026),[nickname,setNickname]=useState('指挥官'),[address,setAddress]=useState(''),[branch,setBranch]=useState('all'),[entry,setEntry]=useState('kimi'),[saves,setSaves]=useState<SaveEntry[]>([]),[saveOpen,setSaveOpen]=useState(false);
  const[roomCode,setRoomCode]=useState(''),[port,setPort]=useState(6066);
  const validJoin=!!address.trim()&&/^[0-9a-f]{6}$/i.test(roomCode.trim());
  const campaign=p.session?.status==='battle'||p.session?.status==='finished',chosen=THEMES.find(t=>t.id===theme)!;
  const selected=p.catalog.items.find(i=>i.id===entry)??p.catalog.items[0];
  useEffect(()=>{if(!saveOpen)return;void v6Request<{saves?:SaveEntry[];items?:SaveEntry[]}>('saves').then(r=>setSaves(r.saves??r.items??[]));},[saveOpen]);
  async function begin(){if(mode==='join'&&!validJoin)return;if(p.session){const result=await p.onAction('leave');if(!result)return;}if(await p.onBegin({mode,theme,seed,nickname,address:mode==='join'?address.trim():undefined,code:mode==='join'?roomCode.trim().toUpperCase():undefined,port:mode==='host'?port:undefined}))if(mode==='solo')p.onContinue();}
  async function load(id:string,replay=false){
    if(saves.find(save=>save.id===id)?.compatible===false)return;
    if(p.session){const left=await p.onAction('leave');if(!left)return;}
    const result=await p.onAction(replay?'replay':'load',{id}) as {session?:V6Session}|null;
    if(result?.session?.status==='lobby'){setMode('host');return;}
    if(result)p.onContinue();
  }
  return <section className="v6-lobby" aria-label="编译防线 V6 行动大厅">
    <div className="v6-lobby-art" style={{backgroundImage:`url(${V6_ART}hub/command-center.png)`}}/>
    <header className="v6-lobby-header"><div className="v6-brand"><span className="v6-brand-symbol">⌘</span><div><b>编译防线</b><small>CODE SENTINELS / VERTICAL FRONT</small></div></div><div className="v6-lobby-status"><i className={p.connected?'online':''}/>{campaign?'行动进行中':'基地攻防 · V6'}<span>LOCAL COMMAND</span></div>{campaign&&<button className="v6-icon" aria-label="关闭大厅返回战场" onClick={p.onContinue}><X/></button>}</header>
    <nav className="v6-lobby-nav" aria-label="大厅导航">{([['operations','行动',Swords],['archive','装备档案',BookOpen],['guide','指挥手册',Layers3]] as const).map(([id,name,Icon])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}><Icon size={17}/>{name}<span>{id.toUpperCase()}</span></button>)}</nav>
    {p.error&&<div className="v6-lobby-error" role="alert">{p.error}<button onClick={p.onRefresh}>重新连接</button></div>}
    {tab==='operations'?<div className="v6-operation-layout"><div className="v6-lobby-copy"><span className="v6-eyebrow">OPERATION 06 / BUILD BEYOND THE SURFACE</span><h1>向上筑城。<br/>向下扎根。</h1><p>从一间毛坯房，到一座算力要塞。<br/>守住能源与补给，把科技化作战场上的优势。</p><div className="v6-lobby-traits"><span><Layers3 size={16}/>八层战场</span><span><Users size={16}/>实时基地攻防</span><span><Clock3 size={16}/>30—45 分钟</span></div>
      {campaign&&<button className="v6-continue" onClick={p.onContinue}><div><small>CONTINUE OPERATION / {timeV6(p.snapshot?.tick??0)}</small><strong>{p.snapshot?.winner?'查看战场结果':'继续当前行动'}</strong></div><ArrowRight/></button>}
      <button className="v6-text-action" onClick={()=>setSaveOpen(!saveOpen)}><FolderOpen size={15}/>存档与回放<ChevronRight size={15}/></button>
      {saveOpen&&<div className="v6-save-list">{saves.length?saves.map(save=><div key={save.id}><span>{save.name??save.id}<small>{timeV6(save.tick??0)}</small>{save.compatible===false&&<small>{save.compatibilityReason??'存档规则与当前版本不兼容，原文件已保留。'}</small>}</span><button disabled={p.busy||save.compatible===false} onClick={()=>void load(save.id)}>读取</button><button disabled={p.busy||save.compatible===false} onClick={()=>void load(save.id,true)}>回放</button></div>):<p>尚无 V6 存档。进入战场后可保存行动。</p>}</div>}
      <footer className="v6-lobby-footnote">摧毁敌方核心，或守住战略节点完成资源压制。<br/>控制矿点、护送补给、切断对手的下一轮投入。</footer>
    </div><aside className="v6-deploy-panel"><span className="v6-eyebrow">DEPLOYMENT / 行动配置</span><div className="v6-mode-tabs">{([['solo','人机攻防'],['host','创建房间'],['join','加入房间']] as const).map(([id,name])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{name}</button>)}</div>
      {p.session?.status==='lobby'?<div className="v6-room-lobby"><Radio/><h2>指挥网络已建立</h2><p className="v6-address">{p.session.address}</p><small>房间 {p.session.code}</small><div className="v6-player-slots">{[1,2].map(owner=>{const player=p.session?.players.find(q=>q.owner===owner);return <div key={owner}><i style={{background:owner===1?'#8bd7c0':'#df998a'}}/><span>{player?.nickname??'等待指挥官'}<small>{player?.connected?'已连接':'空席'}</small></span>{player?.ready?<Check size={18}/>:<span>未准备</span>}</div>;})}</div><button className="v6-primary" onClick={()=>void p.onAction('ready',{ready:!p.session?.players.find(q=>q.owner===p.playerId)?.ready})}>切换准备状态</button>{p.session.mode==='host'&&<button className="v6-primary" disabled={!p.session.players.every(q=>q.ready)||p.session.players.length<2} onClick={async()=>{if(await p.onAction('start'))p.onContinue();}}>开始基地攻防<ArrowRight size={16}/></button>}<button className="v6-text-action" onClick={()=>void p.onAction('leave')}>离开房间</button></div>:<>
        <label className="v6-field">呼号<input aria-label="指挥官呼号" value={nickname} maxLength={24} onChange={e=>setNickname(e.target.value)}/></label>
        {mode==='join'?<div className="v6-join-copy"><Radio size={32}/><h2>接入另一座基地</h2><p>双方运行同版游戏，填写房主分享的地址与房间码。支持局域网及 IP 直连。</p><label className="v6-field">房主 IP:端口<input aria-label="房主IP和端口" placeholder="192.168.1.20:6066" value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="v6-field">六位房间码<input aria-label="房间码" placeholder="例：A1B2C3" maxLength={6} autoComplete="off" autoCapitalize="characters" value={roomCode} onChange={e=>setRoomCode(e.target.value.trim().toUpperCase())}/></label></div>:<><div className="v6-theme-list">{THEMES.map(t=><button key={t.id} aria-pressed={t.id===theme} onClick={()=>setTheme(t.id)}><span>{t.subtitle}</span><strong>{t.name}</strong>{t.id===theme&&<Check size={17}/>}</button>)}</div><p className="v6-briefing">{chosen.text}</p><label className="v6-field v6-seed">地图种子<input aria-label="地图种子" type="number" min="1" max="2147483647" value={seed} onChange={e=>setSeed(Math.max(1,Math.min(2147483647,Number(e.target.value)||1)))}/></label>{mode==='host'&&<><label className="v6-field">游戏端口<input aria-label="游戏端口" type="number" min="1024" max="65535" value={port} onChange={e=>setPort(Math.max(1024,Math.min(65535,Math.trunc(Number(e.target.value)||6066))))}/></label><p className="v6-muted">局域网使用大厅地址；公网直连需使用映射至本机的游戏端口。</p></>}</>}
        <button className="v6-primary" disabled={p.busy||(mode==='join'&&!validJoin)} onClick={()=>void begin()}><span>{p.busy?'接入中…':mode==='solo'?(campaign?'结束当前行动并重新部署':'开始人机攻防'):mode==='host'?'创建对战房间':'加入对战房间'}</span><ArrowRight size={20}/></button>
      </>}
    </aside></div>:tab==='archive'?<div className="v6-archive-layout"><aside className="v6-archive-navigation"><h2>装备与科技档案</h2><div className="v6-branch-filter"><button aria-pressed={branch==='all'} onClick={()=>setBranch('all')}>全部</button>{V6_BRANCHES.map(b=><button key={b.id} aria-pressed={branch===b.id} style={{color:b.color}} onClick={()=>setBranch(b.id)}>{b.name}</button>)}</div><div className="v6-archive-items">{p.catalog.items.filter(i=>branch==='all'||i.branch===branch).map(item=><button key={item.category+item.id} aria-pressed={selected?.id===item.id} onClick={()=>setEntry(item.id)}><span>{item.name}</span><small>T{item.tier}</small></button>)}</div></aside>{selected&&<article className="v6-archive-entry"><div className="v6-archive-portrait"><img src={v6CardImage(selected)} alt={selected.name}/></div><div className="v6-archive-content"><span className="v6-eyebrow">{selected.id.toUpperCase()} / T{selected.tier}</span><h1>{selected.name}</h1><p>{selected.description}</p><div className="v6-archive-stats"><span>采购<b>◈ {formatV6(selected.cost)}</b></span>{selected.power!==undefined&&<span>电力<b>{formatV6(selected.power)}</b></span>}{selected.damage!==undefined&&<span>伤害<b>{formatV6(selected.damage)}</b></span>}{selected.range!==undefined&&<span>射程<b>{formatV6(selected.range)}</b></span>}</div>{selected.skill&&<p>主动能力：{V6_SKILL_NAMES[selected.skill]??selected.skill}</p>}{selected.passive&&<div className="v6-unit-passive"><strong>{selected.passive.name} · 被动</strong><p>{selected.passive.description}</p></div>}<p className="v6-muted">科技取舍来自实际研究成本与持续供给。建设前可以查看设备的分支、等级与费用。</p>{['kimi','gemini','claude','glm','minimax'].includes(selected.id)&&<a href="https://github.com/larcgpt/ai-model-musume" target="_blank" rel="noreferrer">查看公开人物参考与作者来源 ↗</a>}</div></article>}</div>:<V6Guide catalog={p.catalog}/>}
  </section>;
}
